### ISSUE TITLE
Improving-GRSciColl-match-of-Belgian-collection-datasets-SQL.md

### ISSUE THREAD

**Issue by scooleman** [BelgianBiodiversityPlatform/data-publication-bbpf#3]
### Tasks through PostgreSQL databases: 

ref. [data-publication-bbpf / grscicoll-refinements](https://github.com/BelgianBiodiversityPlatform/data-publication-bbpf/blob/main/grscicoll-refinements.md) 

including: 

> Ants formidabel (also change institutionCode: KBVE-SRBE --> RBINS) 
> 
> African Mammalia (collectionCode: Rodentia --> VER-MAM) 
> 
> RMCA Metafro-Infosys - Xylarium (just shorten the institutionCode into RMCA) 

 

The 3 latter mentioned SQL sources contain in total more than 93,000 specimen occurrence records. It'd be great if they could also be integrated in Belgian collections on GRSciColl. Therefore, next adjustments are essential: 

 

- [Formidabel; Belgian Ants Database's subset](https://www.gbif.org/occurrence/charts?basis_of_record=PRESERVED_SPECIMEN&dataset_key=b528799a-2d52-4023-aa02-9ce081e3ca5f): for only the 11,877 specimen-related records (not the human observations) 

- [x] change their institutionCode (agreed by Wouter Deconinck in email 19/12/2023): KBVE-SRBE --> RBINS  

- [x] add institutionID: https://ror.org/02y22ws83 

- [x] change collectionCode: Formidabel --> INV-INS  

- [x] add collectionID: e9d2c520-d9fc-4331-9ed8-73bea2b22af0 

 

- [African Mammalia dataset's subset](https://www.gbif.org/occurrence/charts?basis_of_record=PRESERVED_SPECIMEN&dataset_key=09baff40-d4a3-11dc-8719-b8a03c50a862): for only the 71,966 specimen-related records (not the human observations) 

- [x] add institutionID: https://ror.org/001805t51 

- [x] change collectionCode: Rodentia --> VER-MAM 

- [ ] add collectionID: 3370b9c2-a06d-4523-88f9-2248f46ce853 

 

- [RMCA Metafro-Infosys - Xylarium dataset](https://www.gbif.org/occurrence/charts?dataset_key=b0cb000d-9381-4881-98d9-1594acf59c89): all 10,189 records  

- [x] add institutionID: https://ror.org/001805t51 

- [x] change institutionCode: RMCA-Metafro-Infosys --> RMCA 

- [x] add collectionID: 0a8fed38-0a84-4c4b-a72f-13b9a941f9a4 

Next 3 mentioned SQL sources contain in total more than 176,000 RBINS specimen occurrence records - currently - with issued flag ‘Collection match fuzzy’. To clear those flags next adjustments are essential:  

- [Beetles (Collection of saproxylic and xylobiont) dataset](https://www.gbif.org/occurrence/charts?dataset_key=d3d38190-0c13-11df-b8c6-b8a03c50a862): all 27,810 specimen-related records 
- [x] change collectionCode: INV-ENT --> INV-INS   
- [x] add collectionID: e9d2c520-d9fc-4331-9ed8-73bea2b22af0  

- [Ants from the Paraguayan dry Chaco dataset](https://www.gbif.org/occurrence/charts?dataset_key=0b0bc0f0-bfad-11dd-aa16-b8a03c50a862): all 9,334 specimen-related records 
- [x] change collectionCode: INV-ENT --> INV-INS   
- [x] add collectionID: e9d2c520-d9fc-4331-9ed8-73bea2b22af0  

- [ARABEL dataset's subset](https://www.gbif.org/occurrence/charts?basis_of_record=PRESERVED_SPECIMEN&dataset_key=fc992520-9e66-11dc-8738-b8a03c50a862): for only the 139,635 specimen-related records 
- [x] add collectionID: 731226bb-c623-4658-a59b-ce2fe91f621c

**Comment by andrejjh** [comment]
Arabel dataset republished today with:
- occurrenceStatus= 'PRESENT'
- collectionID='731226bb-c623-4658-a59b-ce2fe91f621c'
- modified='2024-07-02'
other DwC fields unchanged.

**Comment by andrejjh** [comment]
Today, I'm updating Ants and Beetles datasets to :
* include collectionID
* correct collectionCode
* set occurrenceStatus='PRESENT'

**Comment by andrejjh** [comment]
Today, I updated Formidabel DwC view as suggested + occurrenceStatus='PRESENT'.
GBIF Ingestion in progress...

**Comment by scooleman** [comment]
Thanks, yesterday and today, the essential data fields in two above-mentioned RMCA datasets (Xylarium and African Mammals) are fine-tuned at IPT level (instead of SQL db level) to optimise the interlinking with GRSciColl.

**Comment by scooleman** [comment]
Done. Not an issue if some HumanObservation records also have a collectionCode.
